### ISSUE TITLE
Config::enableRoutes

### ISSUE THREAD

**Issue by MGatner** [tattersoftware/codeigniter4-files#17]
Add a Config option to enable/disable routes automatically.

**Comment by ambadyanands** [comment]
Hi. I can see `files/*` routes in many places in the views. If we disable the default routes and write custom routes, how will it actually work? Sorry in advance if there's anything wrong with my assumption, I just don't understand how custom routes will work when the routes are hardcoded in the views.

**Comment by MGatner** [comment]
This Config toggle isn't for supporting custom routes but more for allowing selective implementation or extension. If someone wants to extend the FilesController in **app/Controllers/** they will need to add the same routes to point to their controller instead. I will fetch an example...

**Comment by MGatner** [comment]
Actually I'm not using this override myself anymore 😅 But I could imagine many scenarios where a developer would want to handle routing explicitly, such as adding Filters or only supporting some routes. 

If you want to send a PR to extend routing to be fully-customizable I will consider it.

**Comment by ambadyanands** [comment]
@MGatner Okay, got it. I have already forked the repo assuming that I will be able to make the necessary changes for custom views (#43) and routes myself. But I will need some time, thanks.
