### ISSUE TITLE
Missing dependency: authentication function user_id()

### ISSUE THREAD

**Issue by ershadow786** [tattersoftware/codeigniter4-files#31]
I have installed the package using composer on fresh codeigniter 4 application,but i can't able to run application as i am getting following error 

> Missing dependency: authentication function user_id() 

I have read documentation where,should i define this user_id() function,can somebody give proper workflow for this?

for now i have defined this function in baseController 

```
function user_id()
	{
		
		return (session()->get('user_data')['user_id'] != NULL) ? session()->get('user_data')['user_id'] : NULL;
	}
```

**Comment by MGatner** [comment]
This would normally be provided by your authentication library. The CodeIgniter authentication provision (https://codeigniter.com/user_guide/extending/authentication.html) came after this major version but I will be adding that as a dependency. 

Defining your own function is a fine way to do it, or ensure you are using a package that provides the provision (e.g. follow the Packagist link from the docs above).

**Comment by robdi123** [comment]
same problem here... i hope someone give us a hand about it. thanks

**Comment by MGatner** [comment]
@robdi123 What more are you looking for than my answer above?
